// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('BassetHound.testHandler.KISSmetrics', ['BassetHound']).run(function(BassetHound, $q) {
    return BassetHound.setTestHandler({
      name: "KISSmetrics",
      activeTests: function() {
        return [
          {
            name: "Sample Test One",
            variations: ["caseOne", "caseTwo"]
          }, {
            name: "Sample Test Two",
            variations: ["caseOne", "caseTwo"]
          }
        ];
      },
      registerTest: function(name, variations) {
        var abTimeout, deferred;

        deferred = $q.defer();
        abTimeout = setTimeout(function() {
          return deferred.reject("AB Test Registration Timed Out");
        }, 6000);
        _kmq.push(function() {
          var activeVariation;

          activeVariation = KM.ab(name, variations);
          return deferred.resolve(activeVariation);
        });
        return deferred.promise;
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=KISSmetrics.map
*/
