// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('BassetHound.testHandler.Optimizely', ['BassetHound']).run(function(BassetHound, $q) {
    return BassetHound.setTestHandler({
      name: "Optimizely",
      activeTests: function() {
        var experiments, variations;

        experiments = optimizely.data.experiments;
        variations = optimizely.data.variations;
        return optimizely.data.state.activeExperiments.map(function(experimentID) {
          var experiment;

          experiment = experiments[experimentID];
          experiment.variations = experiment.variation_ids.map(function(variationID) {
            return variations[variationID].name;
          });
          return experiment;
        });
      },
      registerTest: function(name, variations) {
        var deferred;

        deferred = $q.defer();
        setTimeout(function() {
          return deferred.resolve(activeVariation);
        }, 0);
        return deferred.promise;
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=Optimizely.map
*/
