// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('BassetHound.trackers.console', ['BassetHound']).run(function(BassetHound) {
    return BassetHound.registerTracker({
      name: 'console',
      initialize: function() {
        return console.log("BassetHound - Console Tracker Initialized");
      },
      track: function(eventName, metadata) {
        console.group();
        console.log("BassetHound - Track Event Name:", eventName);
        console.log("BassetHound - Metadata:", metadata);
        return console.groupEnd();
      },
      setUserProperty: function(metadata) {
        console.group();
        console.log("BassetHound - Set User Property:", metadata);
        return console.groupEnd();
      },
      identifyUser: function(identifier) {
        console.group();
        console.log("BassetHound - Identify User:", identifier);
        return console.groupEnd();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=console.map
*/
