// Generated by CoffeeScript 1.6.2
(function() {
  var angularModules;

  angularModules = ['BassetHound', 'BassetHound.trackers.console', 'BassetHound.trackers.KISSmetrics', 'BassetHound.testHandler.KISSmetrics'];

  this.APP = angular.module('bh.demo', angularModules);

  this.AppController = function($scope, BassetHound) {
    BassetHound.track("Visited Page");
    return $scope.identifyUser = function() {
      return BassetHound.identifyUser($scope.name);
    };
  };

}).call(this);

/*
//@ sourceMappingURL=demo.map
*/
